# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485a41819c0507e9c445c52a5807e7977d2d5a9a80d716caa5cd3c5bf988501b0ee4053219551ee3c7c06eb86a1d114f8ab529dda2c22200c14c52ae3fbe6147

test:
  secret_key_base: eab61176008969dc0f6b1600afb1521928ed863a1ec27f6e9555be83ab1af7aab2aa629ea8a33e650844638242c10cec143a3075c0ace432903ff05c3d823fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8b96dcb0503ffa8fbc5be3fa9aa6050952cdd6c1dabc29a9f03b0e1839b3abd586377650eb5dd199247576c89cfb7af24066f2ba7900fac6ba5d288f32be421f
